const express = require('express');
const router = express.Router();
const citaController = require('../controllers/cita.controller');
const { verificarToken }= require('../middlewares/tokens');
router.get('/',                  verificarToken, citaController.getAll);
router.get('/ocupados',          verificarToken, citaController.getBloquesOcupados);
router.get('/:id_cita',          verificarToken, citaController.getById);
router.post('/',                 verificarToken, citaController.create);
router.put('/:id_cita',          verificarToken, citaController.update);
router.delete('/:id_cita',       verificarToken, citaController.delete);
module.exports = router;